safe:        	false
auto:       	false
server:      	false
server_port: 	4000
baseurl:    	/

url:          http://timbenniks.nl
live_url: 		http://timbenniks.nl

source:      	.
destination: 	./_site
plugins:     	./_plugins
exclude:      ['Rakefile', 'README']

future:      	true
lsi:         	false
pygments:    	true
markdown:    	maruku
permalink:   	pretty
paginate:  		3

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

environments:
  stage:
    url: http://test.timbenniks.nl
    remote:
      connection: fbenniks@florisbenniks.nl
      path: /usr/share/nginx/www/test.timbenniks.nl
  production:
    url: http://timbenniks.nl
    remote:
      connection: fbenniks@florisbenniks.nl
      path: /usr/share/nginx/www/timbenniks.nl

navigation:
- text: home
  url: /
- text: work
  url: /work/
- text: blog
  url: /blog/
- text: about me
  url: /about/
- text: fitness journal
  url: /fitness-journal/