safe:        	false
auto:       	false
server:      	false
server_port: 	4000
baseurl:    	/

url: 			http://2012.timbenniks.nl
live_url: 		http://2012.timbenniks.nl

source:      	.
destination: 	./_site
plugins:     	./_plugins

future:      	true
lsi:         	false
pygments:    	true
markdown:    	maruku
permalink:   	pretty
paginate:  		3

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

navigation:
- text: Home
  url: /
- text: work
  url: /work/
- text: blog
  url: /blog/
- text: about me
  url: /about/