safe:        	false
auto:       	true
server:      	false
server_port: 	4000
baseurl:    	/

url: 			    http://loclahost:4000
live_url: 		http://2012.timbenniks.nl

source:      	.
destination: 	./_site
plugins:     	./_plugins

future:      	true
lsi:         	false
pygments:    	true
markdown:    	maruku
permalink:   	pretty
paginate:  		3

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

navigation:
- text: Home
  url: /
- text: work
  url: /work/
- text: blog
  url: /blog/
- text: about me
  url: /about/